### ISSUE TITLE
缩放问题

### ISSUE THREAD

**Issue by ferrerobomb** [jyear/-ohos-iconfont#1]
由于iconfont设计图不规范导致有的图标大有的图标小，要是能缩放到同一尺寸就好了

**Comment by ferrerobomb** [comment]
手动缩放解决了

**Comment by ferrerobomb** [comment]
手动缩放解决了

**Comment by jyear** [comment]
设计图问题需要在iconfont上自己手动处理，这个只会根据iconfont的svg数据生成鸿蒙的svg图标
